### PR TITLE
From delimited

### PR DESCRIPTION
**Pull request by ForeverWintr**
This is a WIP implementation of a `from_delimited_no_guess`, which functions similarly to `from_delimited` but without type guessing. It foregoes `np.genfromtxt`, and instead uses the `csv` module exclusively. Once strings have been parsed, it avoids modifying them unless instructed to do so with `dtypes` and `converters` arguments. 

The core functionality is complete, but the tests are failing because I temporarily re-targeted the regular `from_delimited` to use my approach. I was going through the existing tests and making  `from_delimited_no_guess` versions of many of them.

refs #250

### CODE REVIEW

**Comment by flexatone** [comment]
Many thanks for this PR! The approach taken here is similar to what I am working on as a C extension in ArrayKit, so I am happy to see this and will continue to study it. The specialized performance tests will also be useful.

**Comment by flexatone** [comment]
Any thoughts on how you would have handled a case like this:
```python
>>> np.genfromtxt(['False|True|3.4|(3+2j)'], delimiter='|', dtype=None)                                                            
array((False, True, 3.4, 3.+2.j),
      dtype=[('f0', '?'), ('f1', '?'), ('f2', '<f8'), ('f3', '<c16')])
```

If we have only loaded strings, we cannot just `astype` to object:

```python
>>> np.array(('False', 'True', '3.4' , '(3+2j)')).astype(object)                                                                   
array(['False', 'True', '3.4', '(3+2j)'], dtype=object)
```
So assume you intended to handle this sort of case with a `converters` function?

**Comment by ForeverWintr** [comment]
Yes, cases like that are what made me realize a `converters` function was worthwhile. In this case you'd use it like this (writing from memory)

```python
def istrue(s):
    return s == 'True'

sf.Frame.from_delimited_no_guess(
    fp,
    delimiter='|',
    dtypes={'a': np.bool_, "b": np.bool_, 'c': np.float64, 'd': np.complex,},
    converters={'a': istrue, 'b': istrue,'d': complex,},
)
```

**Comment by flexatone** [comment]
Thanks for that example.

But I was imagining that those values were all in one column: the converters function would be rather complex in that case, no?

**Comment by ForeverWintr** [comment]
I see! The converter would indeed be complex in that case. Are you aware of a better option?

In general, I think we should optimize interfaces for the common case, and that case seems uncommon. I added converters because I think there are some common, simple conversions users will need. For more advanced transformations, I think it's fine to deliver the user a frame of strings and let them apply their own conversion code. The fact that they can rely on getting strings for any column they haven't explicitly converted makes that easier.

**Comment by ForeverWintr** [comment]
I'll close this, as I believe it is superseded by #651

**Pull request closed without merging**
